apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: workflows
spec:
  encryptedData:
    .dockerconfigjson: AgBFUmaIgUQp4DfjHilIGZzVf5/P2yt1VAvIezLkD36XGlzlca7tNSgs2d3qBXxrd9Rem6gWQ8YH64JbB3JjjzUpiXF4UvJDoYSDaSvxLc8marP8VXc2TfiDCiTmfF69x3MMad6ZIeAaaC/4Xe1GztiZbvp4+u1Rn3FrRXtwd9FB240Hs6dQ0VDldzDV5NN7pu9UynbSRnFjfiBiaimx2MAcCPUAqYnUzK9vGb9dZ6XixdXS/9skzwt9qjCXoGsSwdfot7dCAAoG41IUoA+qLXoCD4cc4JTDVn2VqNFAOR1ZsEPhiF6jbeJ65U1sd7QXuT5wlIw5cSPlNiNfh9vc5rXH28VoFev54Q7gRvWp93K1l9J1yolZ+PN2KeNl1DSUgfr/qcaxtGAPjTRfLJUrZkFVE/Aq6xvjgjvVDXKhDJJCM94fjfAJ3NIwgW6b239MV8SQQjGwT1oqvsV3MQrUFmVGGo7JbplOegstoS2mM+mMst2mBT8py17KwGd5wsmkWGujRrwyEb8TkYNE3gFXueKtDy353+3AX0DrKXpfcOzrF/w1PAZUf8kdnB56bXDBV+MZ7/KP/HpdUTvvs76edm39pQTZUYL9trckgrhxB4pUvTehKnTvbn5XSf9Q1/mZ3zt6zrMe88+93/d941dqkiHbU8QGWlfPZ/51V4AZw0cUwMJFpbjRv/NPUzTDlyjZnbLL7seZpd9X/Fwdu/h5DpV1TQthv2GHRxUBKKwUrGRNG9+7oJwp4uMGk08MeoUlMZ/o75mQ1Ww4nNbEW/IJ9NjCbDnF2+rJ/q4f92/SgX2Z1DzuqFERDU5NlJdw+tF1x0BOx+jgEp27ncEdgc8Ht+syKshYi2xSl8ax/OYGR9u2kyEZiDMv2JkHV5hz0ClKkzJvM9xXwFmLwrt+r157dUxW2bCUNjZlqEdUUydX9GKGx3U/WAE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: workflows
    type: kubernetes.io/dockerconfigjson

