apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-combined-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: production
  source:
    path: kustomize/overlays/production
    repoURL: https://github.com/contato318/argo-combined-app
    targetRevision: HEAD
    kustomize:
      images:
      - dirceusilva/argo-combined-app:d21d3758a3c07c934fabd2fc9d5869ec23626a90
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true

