apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgAOuqudv7AyffDH8KLTqC39mg1aGlxoFvwmPz+AEDkc8Xl+f3fDzFgxDuwuJPdec8iqmxjTlQxdeN0OKQ0DJkGUbUZyZHlnc2qunxJj4oyWXCx+QFV8tCRqS3xgIhNSpZCOb0b/R70JYpCnROgGFUr16XlfCdagkwaBjwskjtnlqJlw4apK0GAHfTNBHeCkNNCcNOcP1CHp/Tz8HCfg/+OESm8MGtBfvHi/3T/cYVXWjmnsJ2tL7gr3vGYCAYc/0Grfi0k/M2jd7frJz4MP28JhQyXTWfffSSZjWXaov/fINXptPfUFCuBbDXaAtW88F3wpqaS/CR7lXcZWGYLIHfb74IV8co6glNPxDT87Hq3h3DvhL1eDmvwANLDtzWRvMn1axl71s/60P/SC12PwFh+6Q9jVop4o9H8xR/hIC67VV8919mO89XmKYrVYOGoehMabPI8aqxr+Nxd9yNvVh/gghzllzlJ9THzSw0vrM1GsLpwM81QzbHlfBjXrrSTNlcBlOdupYkLbJ3imlIIL7UEhU+LV10anmxZSgYt2wx58K4d3eQLOHNyu2/EdT7PBohHv+iOn0SMxQAkpSuZ4Vmd1G8N1OpCeLZObObG5nSc9juLLUVQDDuySt+BObGlARrn8irFmXMbOho6gc7eAfUvLNSJpYHTZwzZcD3CRFvrWPmt6ajUzg/wsOhVasTWr+cdDTm5SEgZYqwFV7JSfrQ6vGOnU+te68jI8egPZcq2m5ggIXf7pxyJY
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

